#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# A4: 595 x 842 PT
# 
# /1M/1/0/0/0/0 - /interval/scale/extreme/alarm/color/derivate
#

import StringIO,smtplib,httplib,time,sys

from reportlab.pdfgen.canvas import Canvas
from reportlab.lib import pagesizes
from reportlab.lib.utils import ImageReader

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication

ibuff = StringIO.StringIO()# file buffer instance..
fbuff = StringIO.StringIO()

runtime = time.strftime("%d.%m.%Y %H:%M")
logfile = '/var/log/report.log'

interval = {'1M':31,'2W':14,'7D':7,'1D':1}

report = (# email list | locality | interval | M_ID list
	[[removed],'archa'	,'1M'	,42,43,44,45],
	)

#------------

def get_list(rep):
        lst = ''
        for n in range(3,len(rep)):
                lst += str(rep[n]) + '_1-' + str(rep[n]) + '_2'
                if n != len(rep) - 1: lst += '-'
        return lst

#------------

try:# MAIN
	log = open(logfile,'a')
except:
	print('Failed to open log file.')
	sys.exit(1)

if len(sys.argv) != 2:
	log.write('Wrong number of arguments. ' + runtime + '\n')
	sys.exit(2)

for r in report:
	if sys.argv[1] == r[2]:
		try:# GRAPH
			conn = httplib.HTTPSConnection('[removed]','443',timeout=15)
			conn.request('GET','/muzeum/getplotref/' + get_list(r) + '/' + r[2] + '/1/0/1/0/0')
			ret = conn.getresponse()
			if ret.status == 200:
				ibuff.write(ret.read())
				ibuff.seek(0)# return goddamnit..
			conn.close()
		except:
			log.write('Failed to get graph: ' + r[1] + ' ' + runtime + '\n')
			continue
		try:# PDF
			pdf = Canvas(fbuff,pagesize=pagesizes.landscape(pagesizes.A4))
			pdf.setTitle("Amusing Report 1.4")
			pdf.setFont('Helvetica', 10)
			pdf.drawString(50,550,"Amusing Report 1.4")
			pdf.drawString(640,550,"vygenerováno v " + runtime)
			pdf.line(50,545,790,543)
			pdf.drawImage(ImageReader(ibuff),70,50,700,470)
			pdf.line(50,45,790,43)
			pdf.showPage()
			pdf.save()
		except:
			log.write('Failed to create PDF: ' + r[1] + ' ' + runtime + '\n')
			continue
		try:# MAIL
			for addr in r[0]:
				text = "\n\nDobrý den,\n\nAutomatický report pro lokalitu: " + \
					r[1] + \
					"\n\nAmusing NM\n\n------\n\n" + \
					"Tato zpráva je generována bez možnosti příjmu Vaší odpovědi.\n"

				msg = MIMEMultipart()
				msg['From'] = 'Amusing Report <[removed]>'
				msg['To'] = addr
				msg['Subject'] = "Amusing Report - " + runtime
				msg.attach(MIMEText(text,'plain','utf-8'))

				att = MIMEApplication(fbuff.getvalue())
				att['Content-Disposition'] = 'attachment; filename="' + \
					'amusing-report-' + r[1] + '-' + \
					time.strftime("%d_%m_%Y",time.gmtime(time.time() - 86400 * interval[r[2]])) + \
					time.strftime("-%d_%m_%Y") + \
					'.pdf"'
		
				msg.attach(att)

				mail = smtplib.SMTP('[removed]')
				mail.sendmail('[removed]', addr, msg.as_string())
				mail.quit()
		except:
			log.write('Failed to send email: ' + addr + ' ' + runtime + '\n')
fbuff.close()
ibuff.close()
log.close()

