#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# A4: 595 x 842 PT
#

import StringIO,smtplib,httplib,time,sys

from reportlab.pdfgen.canvas import Canvas
from reportlab.lib import pagesizes
from reportlab.lib.utils import ImageReader

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication

ibuff = StringIO.StringIO()# file buffer instance..
fbuff = StringIO.StringIO()

runtime = time.strftime("%d.%m.%Y %H:%M")
logfile = '/var/log/report.log'

report= {'[removed]':('archa','42_1-42_2-43_1-43_2-44_1-44_2-45_1-45_2')}

try:# MAIN
	log = open(logfile,'a')
except:
	print('Failed to open log file.')
	sys.exit(1)

for email in report.keys():
	try:# GRAPH
		conn = httplib.HTTPSConnection('[removed]','443',timeout=15)
		conn.request('GET','/muzeum/getplotref/' + report[email][1] + '/1M/1/0/0/0/0')
		r = conn.getresponse()
		if r.status == 200:
			ibuff.write(r.read())
			ibuff.seek(0)# return goddamnit..
		conn.close()
	except:
		log.write("Failed to get graph. " + " " + report[email][1] + " " + runtime + "\n")
		continue
	try:# PDF
		pdf = Canvas(fbuff,pagesize=pagesizes.landscape(pagesizes.A4))
		pdf.setTitle("Amusing Report 1.3")
		pdf.setFont('Helvetica', 10)
		pdf.drawString(50,550,"Amusing Report 1.3")
		pdf.drawString(640,550,"vygenerováno v " + runtime)
		pdf.line(50,545,790,543)
		pdf.drawImage(ImageReader(ibuff),70,50,700,470)
		pdf.line(50,45,790,43)
		pdf.showPage()
		pdf.save()
	except:
		log.write("Failed to create PDF. " + " " + report[email][1] + " " + runtime + "\n")
		continue
	try:# MAIL
		text = "\n\nDobrý den,\n\nAutomatický report pro lokalitu: " + \
			report[email][0] + \
			"\n\nAmusing NM\n\n------\n\n" + \
			"Tato zpráva je generována bez možnosti příjmu Vaší odpovědi.\n"

		msg = MIMEMultipart()
		msg['From'] = 'Amusing Report <[removed]>'
		msg['To'] = email
		msg['Subject'] = "Amusing Report - " + runtime
		msg.attach(MIMEText(text,'plain','utf-8'))

		att = MIMEApplication(fbuff.getvalue())
		att['Content-Disposition'] = 'attachment; filename="' + \
			'amusing-report-' + \
			report[email][0] + \
			'-' + \
			time.strftime("%d_%m_%Y",time.gmtime(time.time()-86400*31)) + \
			time.strftime("-%d_%m_%Y") + \
			'.pdf"'
		
		msg.attach(att)

		mail = smtplib.SMTP('[removed]')
		mail.sendmail('[removed]', email, msg.as_string())
		mail.quit()
	except:
		log.write("Failed to send email." + " " + report[email][1] + " " + runtime + "\n")
		sys.exit(1)
fbuff.close()
ibuff.close()
log.close()

